# debug-pp configuration file
# ===========================

# List of Haskell module names to exclude from instrumentation
excluded: []

# If true, use the Hoed backend for trace generation.
useHoedBackend: true

# If true then insert a call to debugRun in the main function.
instrumentMain: true

# When the Hoed backend is used, instruct the debug TH wrapper to insert Observable instances for types that derive Generic.
generateObservableInstances: true

# When the Hoed backend is used, instruct the debug TH wrapper to insert Generic instances for types that don't derive Generic.
generateGenericInstances: false

# If the hoed backend is used, insert the ExtendedDefaultRules pragma.
enableExtendedDefaultingRules: true

# List of types excluded from instance generation
excludedFromInstanceGeneration: []

# If true, print a line for every instrumented module.
verbose: false
