name: axel
version: '0.0.11'
category: Language, Lisp, Macros, Transpiler
author: Joshua Grosso
maintainer: jgrosso256@gmail.com
copyright: 2017 Joshua Grosso
license: BSD3
github: axellang/axel
synopsis: The Axel programming language.
description: Haskell's semantics, plus Lisp's macros. Meet Axel – a purely functional, extensible, and powerful programming language.
extra-source-files:
- README.org
- scripts/**/*
ghc-options:
- -Weverything
- -Wno-all-missed-specialisations
- -Wno-implicit-prelude
- -Wno-missed-specialisations
- -Wno-missing-import-lists
- -Wno-missing-export-lists
- -Wno-missing-local-signatures
- -Wno-monomorphism-restriction
- -Wno-safe
- -Wno-unsafe
- -optP-Wno-nonportable-include-path # https://github.com/haskell/cabal/issues/4739
build-tools:
- hpack:hpack
- tasty-discover:tasty-discover
dependencies:
- base
- hpack
- tasty-discover
data-files:
- resources/**/*
library:
  source-dirs: src
  ghc-options: []
  dependencies:
  - aeson
  - ansi-terminal
  - bytestring
  - containers
  - directory
  - filepath
  - freer-simple
  - ghcid
  - hashable
  - haskell-src-exts
  - lens
  - lens-aeson
  - optparse-applicative
  - parsec
  - process
  - profunctors
  - regex-pcre
  - singletons
  - split
  - strict
  - template-haskell
  - text
  - typed-process
  - uniplate
  - vector
  - yaml
executables:
  axel:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - axel
    - containers
    - freer-simple
    - optparse-applicative
tests:
  axel-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-missing-import-lists
    dependencies:
    - axel
    - bytestring
    - containers
    - filepath
    - freer-simple
    - hedgehog
    - lens
    - split
    - tasty
    - tasty-golden
    - tasty-hedgehog
    - tasty-hspec
    - tasty-hunit
    - transformers
    - uniplate
