name: axel
version: '0.0.6'
category: Language, Lisp, Macros, Transpiler
author: Joshua Grosso
maintainer: jgrosso256@gmail.com
copyright: 2017 Joshua Grosso
license: BSD3
github: axellang/axel
synopsis: The Axel programming language.
description: Haskell's semantics, plus Lisp's macros. Meet Axel – a purely functional, extensible, and powerful programming language.
extra-source-files:
- README.org
- examples/**/*
- scripts/**/*
ghc-options:
- -Wall
- -Wcpp-undef
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-simplifiable-class-constraints
dependencies:
- base >=4.11.1 && <4.12
- freer-simple >=1.1.0.0 && <1.2
data-files:
- resources/**/*
library:
  source-dirs: src
  ghc-options:
  - -Wmissing-import-lists
  dependencies:
  - bytestring >=0.10.8 && <0.11
  - directory >=1.3 && <1.4
  - filepath >=1.4.1 && <1.5
  - haskell-src-exts >=1.20.2 && <1.21
  - lens >=4.16.1 && <4.18
  - lens-aeson >=1.0.2 && <1.1
  - optparse-applicative >=0.14.2 && <0.15
  - parsec >=3.1.11 && <3.2
  - process >=1.6.1 && <1.7
  - regex-pcre >=0.94.4 && <0.95
  - singletons >=2.4 && <2.6
  - strict >=0.3.2 && <0.4
  - text >=1.2.2 && <1.3
  - typed-process >=0.2.2 && <0.3
  - vector >=0.12.0 && <0.13
  - yaml >=0.8.31 && <0.11
executables:
  axel-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wmissing-import-lists
    dependencies:
    - axel
    - optparse-applicative >=0.14.2 && <0.15
tests:
  axel-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - axel
    - bytestring
    - filepath
    - hedgehog
    - lens
    - split
    - tasty
    - tasty-discover
    - tasty-golden
    - tasty-hedgehog
    - tasty-hspec
    - template-haskell
    - transformers
