name: lihsp
version: '0.1.0.0'
category: Lisp, Transpiler
author: Joshua Grosso
maintainer: jgrosso256@gmail.com
copyright: 2017 Joshua Grosso
license: BSD3
github: jgrosso/lihsp
extra-source-files:
- README.md
- scripts/**/*
ghc-options:
- -Wall
- -Werror
- -Wmissing-import-lists
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
dependencies:
- base >=4.7 && <5
data-files:
- resources/**/*
library:
  source-dirs: src
  exposed-modules:
  dependencies:
  - directory
  - lens
  - mtl
  - parsec
  - process
  - split
  - text
executables:
  lihsp-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lihsp
    - mtl
tests:
  lihsp-test:
    main: Lihsp/Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
