name: axel
version: '0.0.3'
category: Language, Lisp, Macros, Transpiler
author: Joshua Grosso
maintainer: jgrosso256@gmail.com
copyright: 2017 Joshua Grosso
license: BSD3
github: axellang/axel
synopsis: The Axel programming language.
description: Haskell's semantics, plus Lisp's macros. Meet Axel – a purely functional, extensible, and powerful programming language.
extra-source-files:
- README.org
- examples/**/*
- scripts/**/*
ghc-options:
- -Wall
- -Wmissing-import-lists
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
dependencies:
- base >=4.11.1 && <4.12
data-files:
- resources/**/*
library:
  source-dirs: src
  exposed-modules:
  - Axel.Project
  dependencies:
  - directory >=1.3 && <1.4
  - filepath >=1.4.1 && <1.5
  - lens >=4.16.1 && <4.18
  - lens-aeson >=1.0.2 && <1.1
  - monad-control >=1.0.2 && <1.1
  - mtl >=2.2.1 && <2.3
  - parsec >=3.1.11 && <3.2
  - process >=1.6.1 && <1.7
  - regex-pcre >=0.94.4 && <0.95
  - split >=0.2.3 && <0.3
  - strict >=0.3.2 && <0.4
  - text >=1.2.2 && <1.3
  - typed-process >=0.2.2 && <0.3
  - vector >=0.12.0 && <0.13
  - yaml >=0.8.31 && <0.10
executables:
  axel-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - axel
    - directory >=1.3 && <1.4
