name: axel
version: '0.0.11'
category: Language, Lisp, Macros, Transpiler
author: Joshua Grosso
maintainer: jgrosso256@gmail.com
copyright: 2017 Joshua Grosso
license: BSD3
github: axellang/axel
synopsis: The Axel programming language.
description: Haskell's semantics, plus Lisp's macros. Meet Axel – a purely functional, extensible, and powerful programming language.
extra-source-files:
- README.org
- scripts/**/*
ghc-options:
- -Weverything
- -Wno-all-missed-specialisations
- -Wno-implicit-prelude
- -Wno-missed-specialisations
- -Wno-missing-import-lists
- -Wno-missing-export-lists
- -Wno-missing-local-signatures
- -Wno-monomorphism-restriction
- -Wno-safe
- -Wno-unsafe
- -optP-Wno-nonportable-include-path # https://github.com/haskell/cabal/issues/4739
# Polysemy https://github.com/polysemy-research/polysemy#necessary-language-extensions
- -fplugin=Polysemy.Plugin
- -O2
- -flate-specialise
- -fspecialise-aggressively
build-tools:
- hpack:hpack
- tasty-discover:tasty-discover
dependencies:
- aeson
- ansi-terminal
- base
- bytestring
- containers
- directory
- filepath
- freer-simple
- ghcid
- haskell-src-exts
- hedgehog
- hpack
- lens
- lens-aeson
- optparse-applicative
- parsec
- polysemy
- polysemy-plugin
- process
- profunctors
- random
- regex-pcre
- singletons
- split
- strict
- tasty
- tasty-discover
- tasty-golden
- tasty-hedgehog
- tasty-hspec
- tasty-hunit
- template-haskell
- text
- transformers
- typed-process
- uniplate
- uuid
- vector
- yaml
data-files:
- resources/**/*
library:
  source-dirs: src
  ghc-options: []
  dependencies: []
executables:
  axel:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - axel
tests:
  axel-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - axel
