name: axel
version: '0.1.0.0'
category: Lisp, Transpiler
author: Joshua Grosso
maintainer: jgrosso256@gmail.com
copyright: 2017 Joshua Grosso
license: BSD3
github: jgrosso/axel
extra-source-files:
- README.org
- scripts/**/*
ghc-options:
- -Wall
- -Werror
- -Wmissing-import-lists
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
dependencies:
- base >=4.7 && <5
data-files:
- resources/**/*
library:
  source-dirs: src
  exposed-modules:
  - Axel.Entry
  dependencies:
  - directory
  - filepath
  - lens
  - mtl
  - parsec
  - process
  - split
  - text
executables:
  axel-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - axel
tests:
  axel-test:
    main: Axel/Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
