name: axel
version: '0.1.0.0'
category: Lisp, Transpiler
author: Joshua Grosso
maintainer: jgrosso256@gmail.com
copyright: 2017 Joshua Grosso
license: BSD3
github: jgrosso/axel
extra-source-files:
- README.org
- scripts/**/*
ghc-options:
- -Wall
- -Werror
- -Wmissing-import-lists
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
dependencies:
- base >=4.11.1 && <4.12
data-files:
- resources/**/*
library:
  source-dirs: src
  exposed-modules:
  - Axel.Project
  dependencies:
  - aeson >=1.3.1 && <1.4
  - bytestring >=0.10.8 && <0.11
  - directory >=1.3 && <1.4
  - filepath >=1.4.1 && <1.5
  - ghc ==8.4.3
  - haskell-src-exts >=1.20.2 && <1.21
  - lens >=4.16.1 && <4.17
  - monad-control >=1.0.2 && <1.1
  - mtl >=2.2.1 && <2.3
  - parsec >=3.1.11 && <3.2
  - process >=1.6.1 && <1.7
  - regex-pcre >=0.94.4 && <0.95
  - split >=0.2.3 && <0.3
  - strict >=0.3.2 && <0.4
  - text >=1.2.2 && <1.3
  - typed-process >=0.2.2 && <0.3
executables:
  axel-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - axel
    - directory >=1.3 && <1.4
tests:
  axel-test:
    main: Axel/Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
