name: axel
version: '0.0.12'
category: Language, Lisp, Macros, Transpiler
author: Joshua Grosso
maintainer: jgrosso256@gmail.com
copyright: 2017 Joshua Grosso
license: BSD3
github: axellang/axel
synopsis: The Axel programming language.
description: Haskell's semantics, plus Lisp's macros. Meet Axel – a purely functional, extensible, and powerful programming language.
extra-source-files:
  - README.org
  - scripts/**/*
ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-deriving-strategies
  - -Wno-missing-export-lists
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-safe
  - -Wno-unsafe
  - -optP-Wno-nonportable-include-path # https://github.com/haskell/cabal/issues/4739

  # https://github.com/polysemy-research/polysemy#necessary-language-extensions
  - -fplugin=Polysemy.Plugin
  - -flate-specialise
  - -fspecialise-aggressively
build-tools:
  - hpack:hpack
  - tasty-discover:tasty-discover
dependencies:
  - aeson ==1.4.4.0
  - ansi-terminal ==0.9.1
  - base ==4.13.0.0
  - bytestring ==0.10.9.0
  - containers ==0.6.2.1
  - directory ==1.3.3.2
  - extra ==1.6.18
  - filepath ==1.4.2.1
  - ghcid ==0.7.5
  - hashable ==1.3.0.0
  - haskell-src-exts ==1.22.0
  - hedgehog ==1.0.1
  - hpack ==0.33.0
  - lens ==4.18.1
  - lens-aeson ==1.0.2
  - megaparsec ==7.0.5
  - mono-traversable ==1.0.12.0
  - optparse-applicative ==0.15.1.0
  - polysemy ==1.2.3.0
  - polysemy-plugin ==0.2.4.0
  - prettyprinter ==1.5.1
  - process ==1.6.5.1
  - profunctors ==5.3
  - random ==1.1
  - split ==0.2.3.3
  - tasty ==1.2.3
  - tasty-discover ==4.2.1
  - tasty-golden ==2.3.2
  - tasty-hedgehog ==1.0.0.1
  - tasty-hspec ==1.1.5.1
  - tasty-hunit ==0.10.0.2
  - template-haskell ==2.15.0.0
  - text ==1.2.4.0
  - time ==1.9.3
  - transformers ==0.5.6.2
  - typed-process ==0.2.6.0
  - uniplate ==1.6.12
  - unordered-containers ==0.2.10.0
  - vector ==0.12.0.3
  - yaml ==0.11.2.0
data-files:
  - resources/**/*
# NOTE Keep in sync with `.hindent.yaml#extensions` and `.hlint.yaml#extensions`.
default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - PolyKinds # Required by `Polysemy.makeSem`
  - RankNTypes
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeOperators
library:
  source-dirs: src
  ghc-options: []
  dependencies: []
executables:
  axel:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - axel
tests:
  axel-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - axel
