name: axel
version: '0.0.10'
category: Language, Lisp, Macros, Transpiler
author: Joshua Grosso
maintainer: jgrosso256@gmail.com
copyright: 2017 Joshua Grosso
license: BSD3
github: axellang/axel
synopsis: The Axel programming language.
description: Haskell's semantics, plus Lisp's macros. Meet Axel – a purely functional, extensible, and powerful programming language.
extra-source-files:
- README.org
- scripts/**/*
ghc-options:
- -Wall
- -Wcpp-undef
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-simplifiable-class-constraints
- -optP-Wno-nonportable-include-path # https://github.com/haskell/cabal/issues/4739
# - -F -pgmF debug-pp
build-tools:
- debug:debug
- hpack:hpack
- tasty-discover:tasty-discover
dependencies:
- base >=4.12 && <4.13
- debug >=0.1.1
- freer-simple >=1.2.0.0
- hpack >= 0.31.0
- tasty-discover >=4.2.1
data-files:
- resources/**/*
library:
  source-dirs: src
  ghc-options:
  - -Wmissing-import-lists
  dependencies:
  - bytestring >=0.10.8
  - containers >=0.6
  - directory >=1.3
  - filepath >=1.4.1
  - ghcid >=0.7.1
  - haskell-src-exts >=1.20.2
  - lens >=4.16.1
  - lens-aeson >=1.0.2
  - optparse-applicative >=0.14.2
  - parsec >=3.1.11
  - process >=1.6.1
  - regex-pcre >=0.94.4
  - singletons >=2.4
  - split >=0.2.3
  - strict >=0.3.2
  - template-haskell >=2.14
  - text >=1.2.2
  - typed-process >=0.2.2
  - vector >=0.12.0
  - yaml >=0.8.31
executables:
  axel:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wmissing-import-lists
    dependencies:
    - axel
    - containers >=0.6
    - optparse-applicative >=0.14.2
tests:
  axel-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - axel
    - bytestring
    - containers
    - filepath
    - hedgehog
    - lens
    - split
    - tasty
    - tasty-golden
    - tasty-hedgehog
    - tasty-hspec
    - transformers
