copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- base >= 4.7 && < 5
name: do
version: '0.1.0.0'
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/do
license: BSD3
executables:
  do-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: []
description: Please see the README on GitHub at <https://github.com/githubuser/do#readme>
